export const CHANGE_CURRENCY = "CHANGE_CURRENCY";
export const CHANGE_CATEGORY = "CHANGE_CATEGORY";
export const CHANGE_CURRENT_GOOD = "CHANGE_CURRENT_GOOD";
export const SET_DATA_CURRENT_GOOD = "SET_DATA_CURRENT_GOOD";
export const SET_OPTIONS_GOOD = "SET_OPTIONS_GOOD";
